# Based on a solution from
# https://www.die-welt.net/2021/06/controlling-somfy-roller-shutters-using-an-esp32-and-esphome/

external_components:
  # - source: components
  - source:   
      type: git
      url: https://github.com/Stardust0766/somfy-esp-cover

esphome:
  name: somfy
  comment: "Somfy ESP32 Controller"
  libraries:
    - EEPROM
    - SPI
    #- SmartRC-CC1101-Driver-Lib@2.5.6   # https://github.com/LSatan/SmartRC-CC1101-Driver-Lib
    #- Somfy_Remote_Lib@0.4.1            # https://github.com/Legion2/Somfy_Remote_Lib
    - https://github.com/Stardust0766/SmartRC-CC1101-Driver-Lib#v2.5.6
    - https://github.com/Stardust0766/Somfy_Remote_Lib#v0.4.1

esp32:
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:
  # Set encryption key
  encryption:
    key: !secret somfy_api_encryption_key

# OTA (Over The Air) updates
ota:
  - platform: esphome
    password: !secret somfy_ota_password

# WiFi settings and manual IP adress
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.6.213
    gateway: 192.168.6.1
    subnet: 255.255.255.0
    dns1: 192.168.6.1
  power_save_mode: none
  reboot_timeout: 5min
  # Only use fast connect, if only one repeater is reachable (like in the basement)
  fast_connect: false 

# Sensor definitions for this device
# Please prefix the signal names by the component e.g. "Heating" to get unique sensor names
sensor:
  # Reports the WiFi signal strength/RSSI in dBm
  - platform: wifi_signal 
    name: "Somfy WiFi Signal Strength"
    icon: "mdi:wifi"
    id: somfy_wifi_signal_db
    update_interval: 5s
    unit_of_measurement: "dBm"
    device_class: "signal_strength"
    entity_category: "diagnostic"

  # Reports the WiFi signal strength in %
  - platform: copy 
    name: "Somfy WiFi Signal Quality"
    icon: "mdi:wifi"
    source_id: somfy_wifi_signal_db
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    device_class: ""
    entity_category: "diagnostic"


# This somfy ESP cover external component provides additional parmeters for configuration:
# nvs_name:               Name of the component. Used in the NVS (non volatile storage) to store the rolling code.
# nvs_key:                Key (variable name) in the NVS to store the rolling code of the specific simulated somfy remote.
# remote_code:            Code of the simulated somfy remote. Required to identify the simulated remote at the somfy cover.
# open_duration:          Duration in seconds to open the cover (omit to disable the time-based position feature).
# close_duration:         Duration in seconds to close the cover (omit to disable the time-based position feature).
# my_position:            Motor position for the 'my' position (omit to disable the 'my' position feature).
#                         If the cover isn't moving and the stop button is pressed the cover moves to this position.
# closed_position:        Motor position until where the cover (shutter) is still closed (omit to disable this feature).
# half_closed_position:   Motor position where the cover (shutter) is half closed (omit to disable this feature).
cover:
  - platform: somfy_esp_cover
    id: "somfy1"
    name: "Somfy Shutter Living Room Left"
    device_class: "shutter"
    nvs_name: "somfy"
    nvs_key: "livingleft"
    remote_code: !secret somfy_remote_living_room_left
    open_duration: 51
    close_duration: 49
    my_position: 0.40
    closed_position: 0.20
    half_closed_position: 0.70

  - platform: somfy_esp_cover
    id: "somfy2"
    name: "Somfy Shutter Living Room Right"
    device_class: "shutter"
    nvs_name: "somfy"
    nvs_key: "livingright"
    remote_code: !secret somfy_remote_living_room_right
    open_duration: 51
    close_duration: 49
    my_position: 0.40
    closed_position: 0.20
    half_closed_position: 0.70

  - platform: somfy_esp_cover
    id: "somfy3"
    name: "Somfy Shutter Bedroom Left"
    device_class: "shutter"
    nvs_name: "somfy"
    nvs_key: "bedleft"
    remote_code: !secret somfy_remote_bedroom_left
    open_duration: 51
    close_duration: 49
    my_position: 0.25
    closed_position: 0.20
    half_closed_position: 0.70

  - platform: somfy_esp_cover
    id: "somfy4"
    name: "Somfy Shutter Bedroom Right"
    device_class: "shutter"
    nvs_name: "somfy"
    nvs_key: "bedright"
    remote_code: !secret somfy_remote_bedroom_right
    open_duration: 51
    close_duration: 49
    my_position: 0.25
    closed_position: 0.20
    half_closed_position: 0.70

switch:
  - platform: template
    name: "Somfy Shutter Living Room Left Program"
    turn_on_action:
      - lambda: |-
          ((esphome::somfy_esp_cover::SomfyESPCover*)id(somfy1))->program();
  - platform: template
    name: "Somfy Shutter Living Room Right Program"
    turn_on_action:
      - lambda: |-
          ((esphome::somfy_esp_cover::SomfyESPCover*)id(somfy2))->program();
  - platform: template
    name: "Somfy Shutter Bedroom Left Program"
    turn_on_action:
      - lambda: |-
          ((esphome::somfy_esp_cover::SomfyESPCover*)id(somfy3))->program();
  - platform: template
    name: "Somfy Shutter Bedroom Right Program"
    turn_on_action:
      - lambda: |-
          ((esphome::somfy_esp_cover::SomfyESPCover*)id(somfy4))->program();
